version: '3.3'
services:
  mysql:
    image: mysql:8.0.26
    container_name: mysql_APIMED
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "root"
    ports:
    - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080